[project]
name = "pac-man"
version = "0.2.0"
description = "Pacman 42 School project"
readme = "README.md"
authors = [
    { name = "Kaisar Smailov", email = "ksmailov@student.42heilbronn.de" },
    { name = "Andrei-Olimpiu Balcu", email = "abalcu@student.42heilbronn.de" }
]
requires-python = ">=3.12"
dependencies = [
    "pygame-ce",
]

[project.optional-dependencies]
dev = [
    "flake8",
    "mypy",
    "pytest>=9.0.2",
]


