[project]
name = "pac-man"
version = "0.1.0"
description = "Pacman 42 School project"
readme = "README.md"
authors = [
    { name = "Kaisar Smailov", email = "ksmailov@student.42heilbronn.de" },
    { name = "Andrei-Olimpiu Balcu", email = "abalcu@student.42heilbronn.de" }
]
requires-python = ">=3.10"
dependencies = [
    "flake8",
    "mypy",
    "numpy",
    "pydantic==2.0.1",
    "pytest>=9.0.2",
    "mazegenerator",
]

[tool.uv.sources]
mazegenerator = { path = "packages/mazegenerator-00001-py3-none-any.whl" }

[project.scripts]
pac-man = "pac_man:main"

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"
